### ISSUE TITLE
[Bug]: linode_object_storage_bucket "failed to parse Linode ObjectStorageBucket id"

### ISSUE THREAD

**Issue by Aransh** [linode/terraform-provider-linode#1557]
### Terraform Version

Terraform v1.9.4 on darwin_arm64

### Linode Provider Version

v2.26.0

### Effected Terraform Resources

linode_object_storage_bucket.storage_bucket

### Terraform Config Files

```hcl
terraform {
  required_providers {
    linode = {
      source = "linode/linode"
    }
  }
}

data "linode_object_storage_cluster" "region" {  
  id = "us-iad-1"
}

resource "linode_object_storage_bucket" "storage_bucket" {
  cluster = data.linode_object_storage_cluster.region.id
  label = "test-provider"
}
```

### Debug Output

> data.linode_object_storage_cluster.region: Reading...
> data.linode_object_storage_cluster.region: Read complete after 0s [id=us-iad-1]
> 
> Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
>   \+ create
> 
> Terraform will perform the following actions:
> 
>   \# linode_object_storage_bucket.storage_bucket will be created
>   \+ resource "linode_object_storage_bucket" "storage_bucket" {
>       \+ acl          = "private"
>       \+ cluster      = "us-iad-1"
>       \+ cors_enabled = true
>       \+ endpoint     = (known after apply)
>       \+ hostname     = (known after apply)
>       \+ id           = (known after apply)
>       \+ label        = "test-provider"
>       \+ region       = (known after apply)
>       \+ versioning   = (known after apply)
>     }
> 
> Plan: 1 to add, 0 to change, 0 to destroy.
> ╷
> │ Warning: Deprecated
> │
> │   with data.linode_object_storage_cluster.region,
> │   on main.tf line 14, in data "linode_object_storage_cluster" "region":
> │   14: data "linode_object_storage_cluster" "region" {
> │
> │ This data source has been deprecated because it relies on deprecated API endpoints. Going forward, `region` will be the preferred way to designate where Object Storage resources should be
> │ created.
> │
> │ (and one more similar warning elsewhere)
> ╵
> ╷
> │ Warning: Argument is deprecated
> │
> │   with linode_object_storage_bucket.storage_bucket,
> │   on main.tf line 19, in resource "linode_object_storage_bucket" "storage_bucket":
> │   19:   cluster = data.linode_object_storage_cluster.region.id
> │
> │ The cluster attribute has been deprecated, please consider switching to the region attribute. For example, a cluster value of `us-mia-1` can be translated to a region value of `us-mia`.
> ╵
> 
> Do you want to perform these actions?
>   Terraform will perform the actions described above.
>   Only 'yes' will be accepted to approve.
> 
>   Enter a value: yes
> 
> linode_object_storage_bucket.storage_bucket: Creating...
> ╷
> │ Warning: Argument is deprecated
> │
> │   with linode_object_storage_bucket.storage_bucket,
> │   on main.tf line 19, in resource "linode_object_storage_bucket" "storage_bucket":
> │   19:   cluster = data.linode_object_storage_cluster.region.id
> │
> │ The cluster attribute has been deprecated, please consider switching to the region attribute. For example, a cluster value of `us-mia-1` can be translated to a region value of `us-mia`.
> ╵
> ╷
> │ Error: failed to parse Linode ObjectStorageBucket id :test-provider
> │
> │   with linode_object_storage_bucket.storage_bucket,
> │   on main.tf line 18, in resource "linode_object_storage_bucket" "storage_bucket":
> │   18: resource "linode_object_storage_bucket" "storage_bucket" {

### Expected Behavior

Object storage bucket name "test-provider" is created in region "us-iad-1", terraform finished successfully

### Actual Behavior

Object storage bucket name "test-provider" is created in region "us-iad-1", terraform fails

### Steps to Reproduce

Simply use the example configuration I provided on Linode provider version v2.26.0

This does not happen with provider version <= 2.24.0
But downgrading to 2.24.0 after getting this issue on 2.25.0 still keep the error, so this supposedly corrupts the state... will require a lot of manual cleanup 😵‍💫

**Comment by zliang-akamai** [comment]
Hi @Aransh, thanks for the bug report and sorry about the late response. We are working on a fix which includes recovering logic of the corrupted ID. You can try it out in the PR's feature branch and let us know if that works for you.

**Comment by zliang-akamai** [comment]
The fix has been merged, and the new version of the provider is scheduled to be released in the next week.

**Comment by Aransh** [comment]
@zliang-akamai Just tested v2.28.0 and indeed all looks good now, thanks!
I am wondering though, I'm still getting deprecation warnings telling me to move from "cluster" to "region", but the example in the warning says `'us-mia-1' can be translated to a region value of 'us-mia'`, but what about 'us-mia-2'?

Bottom line - should I update my code, how do I do that with regions such as us-mia-2 and us-iad-2, and how long will the old structure still be supported for?
